MODEL:
  NUM_CLASSES: 12
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("VisDrone_2019__trainval",)
  TEST: ("VisDrone_2019__test", )
SOLVER:
  MAX_ITER: 120000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-3

OUTPUT_DIR: 'outputs/vgg_ssd300_visdrone0413'
